name       : python-rtree
version    : 0.9.7
release    : 3
source     :
    - https://github.com/Toblerity/rtree/archive/refs/tags/0.9.7.tar.gz : 920a3dc3654ee7060b6d99daa2dc51f28a2878333a2ade7916040652df9fa65a
homepage   : https://github.com/Toblerity/rtree
license    : MIT
component  : programming.python
summary    : R-Tree spatial index for Python GIS
description: |
    Rtree is a ctypes Python wrapper of libspatialindex that provides a number of advanced spatial indexing features for the spatially curious Python user.
builddeps  :
    - libspatialindex
    - numpy
    - python-pytest
    - python-wheel
rundeps    :
    - libspatialindex
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
