name       : python-rtree
version    : 1.0.1
release    : 5
source     :
    - https://github.com/Toblerity/rtree/archive/refs/tags/1.0.1.tar.gz : 20891d2fab1aea052ab45c0c747da14aed62967f67e7e79e1ee2eb3010cc7c37
homepage   : https://github.com/Toblerity/rtree
license    : MIT
component  : programming.python
summary    : R-Tree spatial index for Python GIS
description: |
    Rtree is a ctypes Python wrapper of libspatialindex that provides a number of advanced spatial indexing features for the spatially curious Python user.
builddeps  :
    - libspatialindex # check
    - numpy           # check
    - python-pytest   # check
    - python-wheel
rundeps    :
    - libspatialindex
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
