name       : python-rtree
version    : 1.0.0
release    : 4
source     :
    - https://github.com/Toblerity/rtree/archive/refs/tags/1.0.0.tar.gz : b9cc215197cffeb3c7b8becfc6833d382f431381942e5529bcf276a874028fec
homepage   : https://github.com/Toblerity/rtree
license    : MIT
component  : programming.python
summary    : R-Tree spatial index for Python GIS
description: |
    Rtree is a ctypes Python wrapper of libspatialindex that provides a number of advanced spatial indexing features for the spatially curious Python user.
builddeps  :
    - libspatialindex # check
    - numpy           # check
    - python-pytest   # check
    - python-wheel
rundeps    :
    - libspatialindex
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
